name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        deno:
          - v1.9.0
          - v1.9
          - canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}
      - run: ./s cov
      - run: ./s codecov
